### ISSUE TITLE
Unicode error bij aanmaken adressamenvatting

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/housenum-be-r-parser#11]
Volgende foutmelding kreeg ik bij het uitvoeren van het script update_locatie_samenvattingen op test.

```
ERROR:update_locatie_samenvattingen:Script wordt gestopt. Al de vorige updates werden opgeslagen.
    Herstart met '--continue-from 0' om verder te gaan vanaf dit punt
Traceback (most recent call last):
  File "/var/projects/inventaris/venv/bin/update_locatie_samenvattingen", line 10, in <module>
    sys.exit(main())
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/inventaris/scripts/update_locatie_samenvattingen.py", line 137, in main
    start=args.continue_from
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/inventaris/scripts/update_locatie_samenvattingen.py", line 76, in update_locatie_samenvattingen
    verwerk_locatie_samenvattingen(db_object)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/inventaris/views/rest/utils.py", line 460, in verwerk_locatie_samenvattingen
    elementen)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/inventaris/views/rest/utils.py", line 516, in get_straat_summary
    result = create_straat_key(elementen)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/inventaris/views/rest/utils.py", line 511, in create_straat_key
    housenum_string = merge_numbers(housenum_string)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/inventaris/views/rest/utils.py", line 475, in merge_numbers
    number_string, on_exc=ReadException.Action.KEEP_ORIGINAL
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/housenumparser/__init__.py", line 45, in merge
    numbers = split(data, on_exc=on_exc)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/housenumparser/__init__.py", line 28, in split
    numbers = reader.read_data(data, step=step, on_exc=on_exc)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/housenumparser/reader.py", line 44, in read_data
    return read_iterable(str(data).split(","), step=step, on_exc=on_exc)
UnicodeEncodeError: 'ascii' codec can't encode character u'\x85' in position 6: ordinal not in range(128)
```

**Comment by Wim-De-Clercq** [comment]
todo:
```
from builtins import str
```
toevoegen in de `reader.py` file.

Dit neemt natuurlijk niet weg dat er ergens in inventaris iets zit met een huisnummer dat https://www.codetable.net/hex/85 bevat, maar we kunnen er hier wel omheen werken.

**Comment by Wim-De-Clercq** [comment]
Elke file binnen housenumberparser heeft nu 
```
from __future__ import unicode_literals

from builtins import str
```
Indien er strings in de file staan en/of `str()` gebruikt worden.
